name: Trigger Grammar Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch event
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/AbhiTheModder/understand-smali/dispatches \
          -d '{
            "event_type": "grammar-updated",
            "client_payload": {}
          }'
